avatar: "/assets/img/aemy-avatar.svg"

navbar-col: "#006D6D"
navbar-text-col: "#50DDDC"
navbar-border-col: "#50DDDC"
navbar-var-length: true

title: AEMY
repository: hm-aemy/hm-aemy.github.io
url: https://aemy.cs.hm.edu

collections:
  - team

navbar-links:
  Topics:
    - RISC-V ISA Extensions: "topics/risc-v-extensions"
    - Open Source Chip Design: "topics/open-source-chip-design"
    - WebAssembly for Embedded: "topics/wasm4iot"
    - Formal Methods for Embedded: "topics/formal-embedded"
  Projects:
    - ISOLDE: "projects/isolde"
    - Scale4Edge: "projects/scale4edge"
    - DI-OSVISE: "projects/osvise"
    - DI-OCDCpro: "projects/ocdcpro"
  Theses: "theses"
  Jobs: "jobs"
  Team: "team"
